### ISSUE TITLE
Remove offest tracking in Kafka plugins

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1016]
We don't use it anymore

**Comment by woodsaj** [comment]
the offset tracking is only needed when the "offset" for the kafka-mdm-in plugin or kafka-cluster plugin are set to "last".   

This config setting never makes sense.  Data is internally buffered until a "chunk" is filled up, so data will be lost if MT doesn't replay old data at startup (offset=oldest, or offset=<time duration>) ensuring all un-written chunks are restored in their entirety. 

If the user can tolerate the lost data, due to having multiple replicas, then they are better off just using "offset=newest"

So, lets just get rid of "offset=last" support and get rid of the offset tracking.
