### ISSUE TITLE
"fallback-graphite-addr" setting do not support HTTP 1.1

### ISSUE THREAD

**Issue by deniszh** [grafana/metrictank#1027]
I found out that despite http-lookalike format
`fallback-graphite-addr = http://graphite`
fallback-graphite-addr is not really supporting same semantic as e.g. CLUSTER_SERVERS in modern Graphite:
 - Schema should be only http, https is not currently supported
 - HTTP 1.1 is also not supported
 - URL parameters are not supported
I.e. currently `fallback-graphite-addr` is a just another way to set address and port of Graphite server, which is, of course, fine - but can be confusing for new users.

**Comment by deniszh** [comment]
I can create a PR for fixing documentation in `docs/config.md` and example metrictank.ini, but not sure is that a good way to address this issue.

**Comment by Dieterbe** [comment]
to be clear, we parse that value into a URL and then use httputil.NewSingleHostReverseProxy, yielding a `httputil.ReverseProxy`.
* afaik it should support https. what exactly happened when you tried to use https in the url?
* what http1.1 features are broken, meaning what did you do exactly, what happened and what did you expect?
* "URL parameters are not supported" are you saying the parameters are not accepted by our config validation or that they don't show up at graphite's end?

**Comment by deniszh** [comment]
Yes, I checked a code.
1. when I used https first I got some ssl error because `/etc/ssl/certs` was mounted, but when I fixed that I was getting instant "proxy error"
2. At least looks like it's not putting proper "Host" header. I need to make some test setup to proper investigation, not sure if I will have time for that soon, unfortunately
3. That alos require additional investigation.
TBH I'm not sure if it should be fixed codewise. I see some usecases for proper HTTP semanic (like HTTPS, dynamic ports through proper HTTP balancer) but it can be not worth efforts now.
But informing others about potential issue can be useful.

**Comment by woodsaj** [comment]
The proxying is just a standard HTTP connection.  MT will default to trying http2, but will fallback to http1.1

The request is being **proxied** to Graphite, it is not  a new request.  So the original headers received from the user, including the HOST header, will be forwarded through to the Graphite server.

So because of this, you cant have both graphite and MT sitting behind the same loadbalancer on the same port.  Otherwise, the request will hit the LB, based on the HOST header the LB will send the request to MT.  MT will then proxy the request back to the LB with the same HOST header.  The LB will then route that request to MT creating your loop.

The proxy approach is definitely something that we rely on.   eg, when a request is sent to MT it includes the required "x-org-id" header.  When we proxy, that header gets sent to graphite.  Graphite then has the header listed in the `REMOTE_STORE_FORWARD_HEADERS` setting so that it then gets forwarded through to MT when the backend requests are made to fetch data.

The proxy approach also ensures that we dont need to read the response from graphite.  It is just streamed directly back to the user.

So, i think the proxy approach is the right solution, but i do believe that the HOST header should be that of the Graphite server and not the original HOST header the user used for connecting to MT.  Fixing that should be easy.

@Dieterbe  thoughts?

**Comment by Dieterbe** [comment]
> The proxy approach is definitely something that we rely on ... it includes the required "x-org-id" header. When we proxy, that header gets sent to graphite ... we dont need to read the response from graphite. It is just streamed directly back to the user.

both of these things we could still do if it was a fresh request, just with a bit more work. though doing the 2nd (streaming a response to the user that was a response for a request different than the one the user sent) is probably asking for trouble and/or more hackery.

> So, i think the proxy approach is the right solution, but i do believe that the HOST header should be that of the Graphite server and not the original HOST header the user used for connecting to MT. Fixing that should be easy.

this seems reasonable. would this work for you @deniszh ? does this mean we need to add an additional config flag to MT to know the hostname to use?

**Comment by woodsaj** [comment]
>  does this mean we need to add an additional config flag to MT to know the hostname to use?

No.  We already have the hostname to use. it is the hostname of the the server specified in the fallback-graphite-addr setting.

from: https://golang.org/pkg/net/http/httputil/#NewSingleHostReverseProxy
> NewSingleHostReverseProxy does not rewrite the Host header. To rewrite Host headers, use ReverseProxy directly with a custom Director policy.

So we just need to create our own ReverseProxy with a custom Director in
https://github.com/grafana/metrictank/blob/master/api/graphite_proxy.go#L38

**Comment by deniszh** [comment]
> The request is being proxied to Graphite, it is not a new request. So the original headers received from the user, including the HOST header, will be forwarded through to the Graphite server.

Ah, that making sense, thanks for the clarification, @woodsaj !

>>So, i think the proxy approach is the right solution, but i do believe that the HOST header should be that of the Graphite server and not the original HOST header the user used for connecting to MT. Fixing that should be easy.

>this seems reasonable. would this work for you @deniszh ?

Yes, definitely. I switched to Consul routing, but logic above has more sense for me, indeed.
Thanks!
