### ISSUE TITLE
Keep track of out-of-order metrics

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1048]
Multiple times I've had that situation that a customer sent us out of order data, but they didn't know why exactly their data lost the order. When trying to debug the issue a common question is "Which metrics have received out of order data?". Usually I'm using the tool `mt-kafka-mdm-sniff-out-of-order` to pull a bunch of metric IDs out of kafka, because with the MetricPoint format we unfortunately can't directly obtain the metric names anymore, and then looked up the metric IDs from the index manually. This is tedious and the result is a very incomplete sample. It would be better if Metrictank could keep track which metrics have received data that was out of order and could provide a list with the names of those metrics.

**Comment by Dieterbe** [comment]
implementation ideas:
1) extend mt-kafka-mdm-sniff-out-of-order to return proper metric names (those should pass by every 6hours, and if not, query index)
2) each AggMetric could report back to another structure (list) when OOO happens.this list can then be fetched via an api call.
3) similar to 2, but AggMetric could track a "last out of order seen" timestamp. to get the overview, we would then have to iterate over all AggMetrics. note that info would get lost per `metric-max-stale` pruning
4) report out of orders to the index. but that would create more coupling which i don't like, and is also subject to pruning.

2 seems most practical, but needs a bit more thought

**Comment by replay** [comment]
2. sounds good. The problem with it is that if a metric receives multiple OOO datapoints we'll not want it to get added to the list multiple times, so we'd need some kind of hashing to be able to check which metric is already on the list. Instead of using an actual list we could use a `map` of `MKey`s, that way it is relatively memory efficient because `MKey`s are small and the lookup inside the map is fast.

**Comment by Dieterbe** [comment]
> I think it should be possible to enable/disable that tracking via some API call, because we don't need to have it running at all times.

i thought the whole point was to be able to provide a report that goes back in time (e.g. showing all out of order metrics seen in the last multiple weeks). if we only need to start collecting data when the need arises instead of earler, then I like option 1 more. we could just create a job to run the tool in the background and generate a report. there doesn't need to be any manual involvement.

**Comment by replay** [comment]
Even if we implement 2) we couldn't realistically show a complete set of metrics over the past multiple weeks because sooner or later MT instances always get restarted and moved around between nodes etc. 
I think you're right, a relatively simple solution that would satisfy what we want to do would be to change `mt-kafka-mdm-sniff-out-of-order` so it can lookup metric IDs from the index, then we could add some mechanism to spin this job up as a k8s job which runs for X hours and then returns a list.

**Comment by woodsaj** [comment]
given the frequency of issues, i think just fixing mt-kafka-mdm-sniff-out-of-order  would be good enough for now.
To support getting the series from id, we need to update MT to provide an API to query for a series from an id.  there is "/index/get" already, but it expects an MKey, so you have to query using
```
curl http://localhost:6060/index/get -H "content-type: json" -d '{"id":{"Key":[67,97,58,94,115,8,21,102,225,59,33,194,196,231,156,98],"Org":5000}}'
```
instead of just
```
curl http://localhost:6060/index/get?id=5000.43613a5e73081566e13b21c2c4e79c62
```
and the api only returns msgp response.
