### ISSUE TITLE
graceful handling of storage-schemas.conf changes

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1144]
when storage-schemas.conf is adjusted:
* when TTL for a certain retention is changed. MT starts looking in a different table (IIRC bigtable store is not affected, but for cassandra/scylladb we use different tables based on TTL of the data.)
* when interval of a rollup changes, it won't be aware of the past data.

I'ld like to solve this.
One idea I have is to extend the store schema to include a schemas table that would store all the different versions of schemas seen, and when the switch was made from one version to another. (only write nodes would write to this, but all nodes would read from it)
Based on this, it could figure out how to handle the above cases.

**Comment by woodsaj** [comment]
You can only drop sstables from Cassandra when all data in the sstable is expired.  If you don't set a TTL when the data is written, then the data will never expire.

For MT to be able to handle data cleanup we would have to use a completely different schema to what we have today.  "Deleting" in Cassandra involves writing a tombstone.  Data is then only removed from disk when sstables are compacted.  Writing these tombstones and continually compacting sstables would add a significant amount of load on Cassandra.

The only viable option I can think of would be to use daily/weekly tables.  MT could then just drop entire tables based on retention.

**Comment by shanson7** [comment]
One of the reasons that @Dieterbe and I were discussing this is that we are re-evaluating our retention policies. We want to keep data longer, but updating the 100TB+ of existing cassandra data is unrealistic and exceptionally expensive. We are also hesitant to make a decision too early, since it is *very* difficult to undo with the current design. That's why I lean toward a design that would make these changes more flexible and dynamic, and that's just not something that Cassandra TTLs support at this scale. I agree with @woodsaj that a table bucketing scheme is probably the easiest solution.

The basic solution that I think makes sense is to use tables like the existing partition keys (which have a monthly-ish time bucket):
`metric_<schema_name>_<series-interval>_<time bucket>`
 
where `time_bucket` can be more or less coarse based on the interval or a hint in the conf file (not the retention, unfortunately, since that can change). 

So a schema like:
```
[mydata]
pattern = ^mydata\..*
retentions = 1s:30d:90m:2,5m:90d:4h:2,1h:400d:4h:2
```
would generate tables like:

```
metric_mydata_1s_17875   # table per day 
metric_mydata_5m_2553    # table per 7 days 
metric_mydata_1h_638     # table per 28 days
```

The `time_bucket` interval would represent the minimum granularity for storage reclamation (since we drop a table at a time) but the actual retention policy can be easily enforced by bounding the query. 

The downside to this approach is that if there are a large number of schema patterns, then there will be more "hot" tables (tables being written to) which means more memtables in cassandra, more memory usage.

**Comment by shanson7** [comment]
Note that the above solution is quite similar to the behavior of TWCS, except that with TWCS the TTL lives with the data.

**Comment by biancalana** [comment]
It's not totally related to this thread, but how can I change the retention and keep historic data ? I have much less data than @shanson7 describes here, so even updating cassandra is viable for me. I just can't realize how to do that.

**Comment by 6d6178** [comment]
I have the same question as @biancalana regearding changing the retention. I would like to be able to change the retention after the initial setup like you do with whisper-update.

**Comment by Dieterbe** [comment]
@biancalana , @6d6178 sorry for the extremely late reply, but you can use the `mt-update-ttl` tool that comes with metrictank to do exactly that. it will adjust the data in cassandra.
