### ISSUE TITLE
Add tags to exported Metrictank stats

### ISSUE THREAD

**Issue by robert-milan** [grafana/metrictank#1294]
We need to add a duplicate set of exported stats to Metrictank in order to facilitate the transition to a mostly tag based system.

For a yet to be determined amount of time we should export both the current stats and the new stats with tags to allow alerts and queries to be updated accordingly. This will temporarily increase memory usage.

This will also be a great opportunity to gather data on the memory usage reductions provided by #1212 

Examples of proposed tagged stats:

### `memory.gc.cpu_fraction`
**Old Stat**
```
metrictank.stats.$environment.$instance.memory.gc.cpu_fraction.gauge32
```
**New Stat**
```
memory.gc.cpu-fraction;application=metrictank;environment=$environment;instance-id=$instance;metric-type=gauge32
```

### `api.request.node.latency`
**Old Stat**
```
metrictank.stats.$environment.$instance.api.request.node.latency.mean.gauge32
```
**New Stat**
```
api.request.latency;application=metrictank;environment=$environment;instance-id=$instance;http-path=node;metric-aggregation=mean;metric-type=gauge32
```

### `idx.memory.find-cache.invalidation.drop`
**Old Stat**
```
metrictank.stats.$environment.$instance.idx.memory.find-cache.invalidation.drop
```
**New Stat**
```
idx.memory.find-cache.invalidation;application=metrictank;environment=$environment;instance-id=$instance;metric=drop;metric-aggregation=mean;metric-type=gauge32
```

### `idx.memory.find-cache.invalidation.exec`
**Old Stat**
```
metrictank.stats.$environment.$instance.idx.memory.find-cache.invalidation.exec
```
**New Stat**
```
idx.memory.find-cache.invalidation;application=metrictank;environment=$environment;instance-id=$instance;metric=exec;metric-aggregation=mean;metric-type=gauge32
```

You might be wondering why I am proposing to use such long tag `keys` and `values`. The length of the tag `key` and `value` don't matter much when using #1212. All of the terms will be stored once as `byte` slices in the object store and many times as `uintptr`s in `Metrictank` itself, so being more verbose is not an issue.

Each series will need to be inspected individually to determine the exact series name / tag combinations.

**Comment by robert-milan** [comment]
@Dieterbe @replay @fkaleo @woodsaj 
Thoughts?

**Comment by Dieterbe** [comment]
1) for certain values, it is implied that is an id. so instance-id can simply be instance.
2) metrictype -> mtype (per metrics2.0), though it only allows for gauge, not gauge32 , etc. see http://metrics20.org/spec/#tag-values-mtype for the implementation of our current stats library i thought it would be neat to add the datatype/valuerange as part of this, but i messed it up because i failed to disambiguate uints from ints anyway. i still like the idea, but if we publish as mtype we will have to enable some of these new values in our validation (not a lot of work), and this time we can do it right and properly use values such as gauge_uint32 vs gauge_int32
3) metric-aggregation -> `stat` (http://metrics20.org/spec/#tag-values-stat)
4) maybe application -> app. i would lean towards brevity for tags that will be very commonly used, though i don't have a hard opinion on this.
5) `metric=drop` -> `metric` is too vague. every property of the metric (the name and all tags) describe "the metric", so try harder to avoid using names like "metric". I generally use "operation" for stuff like this. Also, only separate this out into a tag if there will definitely be several possible versions of this name and tag combination, but for a different operation. if not, just add the `.drop` to the metric name

**Comment by robert-milan** [comment]
> 1. for certain values, it is implied that is an id. so instance-id can simply be instance.

Sounds good

> 2. metrictype -> mtype (per metrics2.0), though it only allows for gauge, not gauge32 , etc. see http://metrics20.org/spec/#tag-values-mtype for the implementation of our current stats library i thought it would be neat to add the datatype/valuerange description to the value, but i messed it up because i failed to disambiguate uints from ints anyway. i still like the idea, but if we publish as mtype we will have to enable some of these new values in our validation (not a lot of work), and this time we can do it right and properly use values such as gauge_uint32 vs gauge_int32 (or gauge_32 and gauge_u32)

I'm open to this as well, let's discuss the details a little bit further

> 3. metric-aggregation -> `stat` (http://metrics20.org/spec/#tag-values-stat)

I'm ok with changing it to `stat`. I typically prefer more verbose names when it doesn't come at a huge cost.

> 4. maybe application -> app. i would lean towards brevity for tags that will be very commonly used, though i don't have a hard opinion on this.

Same as above

> 5. `metric=drop` -> `metric` is too vague. every property of the metric (the name and all tags) describe "the metric", so try harder to avoid using names like "metric". I generally use "operation" for stuff like this. Also, only separate this out into a tag if there will definitely be several possible versions of this name and tag combination, but for a different operation. if not, just add the `.drop` to the metric name

Agreed, `metric` may be a bit vague here. I'll give it some more thought.

**Comment by replay** [comment]
If we do that, should we still leave the tag support to be optional? 
The only disadvantage that I can see of always enabling the tag index is that it is going to consume more memory, because even if there are no real tags then the names still get indexed as a tag. Although the interning PR should help with that.

**Comment by shanson7** [comment]
Re: `stat` as a tag, I like to follow the naming guide of prometheus https://prometheus.io/docs/practices/naming/

Namely 
>As a rule of thumb, either the sum() or the avg() over all dimensions of a given metric should be meaningful (though not necessarily useful). If it is not meaningful, split the data up into multiple metrics. For example, having the capacity of various queues in one metric is good, while mixing the capacity of a queue with the current number of elements in the queue is not.

So, `sum()`/`avg()` of series where `mean` `median` and `max` are all dimensions is awkward.

**Comment by Dieterbe** [comment]
@shanson7 what's the alternative? graphite doesn't have a histogram type, unlike prometheus. it seems that's the reason we're in this pickle.

**Comment by shanson7** [comment]
We put them in the metric name as a suffix.

**Comment by robert-milan** [comment]
> If we do that, should we still leave the tag support to be optional?

We should turn tag support on by default at this point.

> The only disadvantage that I can see of always enabling the tag index is that it is going to consume more memory, because even if there are no real tags then the names still get indexed as a tag. Although the interning PR should help with that.

Currently the interning PR will not help with reducing the cost of the `name` tag. It is on the list, but I'm not sure it will make it into `V1` as it requires many more changes. I would like to implement it because I am not satisfied with the current savings, and I believe it help quite a bit with reducing memory usage.

**Comment by robert-milan** [comment]
I think it makes sense to keep the `metric-aggregation` (or `stat`) tag. I don't know if it conforms to the other standards, but it feels natural to be able to just swap out the tag to get the results you want instead of changing the series you are querying for. After all, they are just different representations, but the core concept of what is being tracked and analyzed remains the same.

For example:
`api.request.latency` is a fairly broad concept. Some of its properties include the `http path`, `mtype`, and in my opinion `stat`.

I am fine with implementing whatever we can agree on.

**Comment by Dieterbe** [comment]
I think Sean's point makes sense for prometheus because with prometheus you can just do `avg(metric{})` and it'll aggregate across all different series (tag values) of that metric.
Whether it makes sense here depends on whether:
1) the same is true for Graphite, or
2) with Graphite you have to opt-in to each tag key you want to aggregate across.

I'm not very familiar with aggregations across tags in graphite, but it looks like 1 is the case.

**Comment by DanCech** [comment]
This all seems reasonable to me, I took a stab at streamlining the initial example and came up with this (the biggest difference being moving the index type into a tag).

As for aggregating across series, graphite provides `aggregate`, `aggregateWithWildcards` and `groupByTags`/`groupByNodes`.

Examples of proposed tagged stats:
### `memory.gc.cpu_fraction`

**Old Stat**

```
metrictank.stats.$environment.$instance.memory.gc.cpu_fraction.gauge32
```

**New Stat**

```
memory.gc.cpu-fraction;app=metrictank;env=$environment;instance=$instance;mtype=gauge32
```

### `api.request.node.latency`

**Old Stat**

```
metrictank.stats.$environment.$instance.api.request.node.latency.mean.gauge32
```

**New Stat**

```
api.request.latency;app=metrictank;env=$environment;instance=$instance;http-path=node;stat=mean;mtype=gauge32
```

### `idx.memory.find-cache.invalidation.drop`

**Old Stat**

```
metrictank.stats.$environment.$instance.idx.memory.find-cache.invalidation.drop
```

**New Stat**

```
idx.find-cache.invalidation;app=metrictank;env=$environment;instance=$instance;metric=drop;stat=mean;mtype=gauge32;idxtype=memory
```

### `idx.memory.find-cache.invalidation.exec`

**Old Stat**

```
metrictank.stats.$environment.$instance.idx.memory.find-cache.invalidation.exec
```

**New Stat**

```
idx.find-cache.invalidation;app=metrictank;env=$environment;instance=$instance;metric=exec;stat=mean;mtype=gauge32;idxtype=memory
```

**Comment by Dieterbe** [comment]
1) @DanCech what's the easiest way to confirm aggregation behavior across tags per my and sean's previous comments? didn't see a dashboard on play.grafana.org nor any tagged data in ops
2) again `metric` as a tag is too vague. why not `operation` ?

**Comment by shanson7** [comment]
@dieterbe 

If you do `avg(seriesByTag('name=idx.memory.find-cache.invalidation.exec'))` it will average across all dimensions producing just one result series. In fact, you would have to opt *out* per tag by using a function like `groupByTags(avg, 'operation')`

**Comment by Dieterbe** [comment]
OK, in that case it seems to make more sense to make the stat part of the metric name (just add it to the end). arguably likewise for operation. 

"idx.find-cache.invalidation" doesn't really convey what it is actually measuring, and i'm also confused about why `stat=mean` is being introduced (both in dan's and roberts proposals) on a metric that is merely a running counter and is not aggregated yet. (which btw should result in `mtype=counter_u32` or something, not gauge)

**Comment by DanCech** [comment]
That seems sane enough to me, omitting a tag or passing it with an empty value are treated the same at query time.

**Comment by Dieterbe** [comment]
This project has been deprioritized, but this conversation is still useful, so just wanted to put more thoughts (or one thought, rather):
[the rule of thumb around meaningfullness of aggregation across all tags](https://github.com/grafana/metrictank/issues/1294#issuecomment-487080475) also implies that the mtype should be encoded as part of the metric name, and not a tag.

**Comment by Dieterbe** [comment]
another reason why this would be very practical is then we can leverage meta tags.

* we can add meta tags for which node the host in, so we can get breakdowns or filters by k8s node (because e.g. a node may be low on resources)
* we can add meta tags to describe whether the pod is in ready state or not. often i want to see stats only for ready pods (e.g. "stable memory usage" vs "startup memory usage")
