### ISSUE TITLE
Maintain "lastQueried" timestamp in index

### ISSUE THREAD

**Issue by DanCech** [grafana/metrictank#1312]
It would be useful to be able to tell the last time that a given series was queried, which we could do by keeping a `lastQueried` timestamp in the index.  This would be useful in determining which series are being stored but not queried, and could potentially be used as an input for more advanced index pruning strategies in the future.

**Comment by Dieterbe** [comment]
just brainstorming here... instead of spending say 32bits for every series, we could also use a 32bitset (or 64 or 128) wherein each bit represents a certain timeframe of decreasing granularity (perhaps corresponding to chunk sizes or data resolution as defined in storage-schemas.conf)
this would allow us to see not just when a serie was queried last (though that would now be an approximation) we'd also see the patterns over time, and be able to get stats such as number of distinct "actively queried series" at each point in time. though there's easier ways to get that (e.g. hash actively queried series into a count sketch)

**Comment by replay** [comment]
We can probably make this update an atomic operation to not have to acquire a write lock to update the `lastQueried` timestamp.

**Comment by Dieterbe** [comment]
we have decided to instead:
1) have proper query logging
2) build a tool that can parse all patters from the query logs and execute those against a metrictank api to be able to see which metrics are being queried.

to see the metrics which are not being queried, one can use `mt-index-cat` + `comm`
