### ISSUE TITLE
We need to be able to restrict the whisper importer utility to a single org

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1334]
Currently when we spin up the importer-writer utility, then it will just write all the chunk write requests it receives into the defined keyspace. But we need to be able to limit which orgs we want to write to, in order to not accidentally write into the wrong one.

**Comment by woodsaj** [comment]
I think this problem needs a bit more thought.
I dont think that we should put restrictions on mt-whisper-importer-writer.   I think the better way to handle this is in the same way we handle metric ingestion, ie we have tsdb-gw authenticate requests and do org-id enforcement.

**Comment by replay** [comment]
That's a good idea. If we support the same authentication mechanism that the normal metric ingestion uses maybe we won't need to deploy the importer-writer every time we need it for a customer on the shared instance. The shared instance could just always have an importer-writer pod running, and if a customer wants to import data they'd simply run the importer-reader with the same authentication key that they use for ingest.

**Comment by replay** [comment]
How about this: https://github.com/grafana/metrictank/pull/1335/commits/0e0a5cdc1d3237cb1aceee0b7da49301958b2dc7

**Comment by Dieterbe** [comment]
i don't think we should move auth into any of the mt services
we already have decent separation of concerns: tsdb-gw doing auth, and after auth, forwarding/proxying requests to MT. why can't we do the same for the importer? just put a tsdb-gw in front which takes care of the auth, that's what it's for.

**Comment by woodsaj** [comment]
I agree with @Dieterbe.  Authentication should continue to remain out-of-scope for metrictank.  
importer-writer should handle auth the same way as metrictank, ie just expect the 'x-org-id' header.  

In addition to just gating access, we also need to ensure that the orgId used in archives matches the orgId of the authenticated user.    For metrics, we currently handle this in tsdb-gw.  We could also handle it there for the importer, but that would mean that the gateway needs to decode the archives and validate that the correct orgId is being used (we could also potentially just modify the orgId in archives before forwarding to the importer, we do that for metrics).   But this seems like unnecessary overhead for archives.  Instead i think we could design it like so:

importer-writer should have a cli flag for orgId enforcement.  If enabled then importer-writer will expect requests to have a 'x-org-id' header.  The value of the header will be the orgId that should be used to validate archives (i am undecided as to whether we should reject or just rewrite).

For GrafanaCloud we then just need to add a proxy route to tsdb-gw for the importer, with the "x-org-id" header being added before proxying the request.  This is exactly what we do for graphite/* requests.

**Comment by Dieterbe** [comment]
I see 3 main options:

## enforce proper orgid in tsdbgw-auth (rewriting orgid based on auth like ingest)
* con: extra decoding (and possibly encoding in case of auth mismatch - rare) overhead 

## enforce proper orgid in imporer-writer via a cli flag
* con: we can't just have an importer-writer running to satisfy imports of different / arbitrary customers.

## enforce proper orgid in imporer-writer by tsdbgw specifying it to importer-writer (e.g. via the http x-org-id header)
* pro: doesn't have the cons of above approaches
* con: this doesn't seem very clean: data on the wire may be inconsistent, and do we want this concern in the mt-importer-writer? it's also inconsistent with our ingestion path.

Note also that the ArchiveRequest not only contains an orgid in its MetricData property, but each contained ChunkWriteRequest has an orgid in the AMKey.
so regardless of which services takes care of auth/validation, either:
* we should also validate that the orgid in the AMKey reflects the orgid of the MetricData (in addition to checking the orgid against the auth)
* the ArchiveRequest should use a slightly different type of CWR, one that uses a new key type AKey (archive key, but not containing an orgid). it should be trivial to convert this CWR type into the one we already have. this enables us to validate much quicker (only in 1 place per ArchiveRequest instead of N), and in theory it means we only need to decode the beginning of the ArchiveRequest instead of having to decode the whole thing (not sure how practical this is though)

**Comment by woodsaj** [comment]
> **enforce proper orgid in imporer-writer via a cli flag**
con: we can't just have an importer-writer running to satisfy imports of different / arbitrary customers

I originally thought this was the case, but i dont think it is.  We could simply pass a different x-org-id with each request.  Unlike with metrics, a single request to importer-writer wont contain data for multiple customers.

**Comment by replay** [comment]
I like `3)` as well. If we do that, does the user even need to specify the org id when starting the reader? If the user will need to specify their authentication credentials anyway, then we might as well just set the org id to 0 in the reader and encode that in the MetricData, then the writer can just take the id from the `X-Org-Id` header and add it to the MetricData before writing to the store. That way the user has one less option to specify when using the reader, so usability is better: https://github.com/grafana/metrictank/blob/master/cmd/mt-whisper-importer-reader/main.go#L51

**Comment by Dieterbe** [comment]
No point arguing about minor nuances. I'm fine with option 3.
@replay regarding your question, probably you're right. but i'ld like @woodsaj  to confirm.

**Comment by replay** [comment]
This is now involving 3 PRs (and I'll need to create one for raintank/schema too):
https://github.com/grafana/metrictank/pull/1335
https://github.com/raintank/tsdb-gw/pull/164
https://github.com/raintank/hosted-metrics-api/pull/241

**Comment by replay** [comment]
I have done more testing of this on Friday (and added a bunch of fixes). If you get a chance, these two are still waiting for review:

https://github.com/grafana/metrictank/pull/1335
https://github.com/raintank/hosted-metrics-api/pull/241

**Comment by Dieterbe** [comment]
With all this discussion having happened I think a synopsis is worthwhile. Seems it all boils down to:

1) tsdbgw provides auth and proxies to importer writer, setting the x-org-id and passing along the client's ArchiveRequests unaltered.
2) currently ArchiveRequest has orgid and AMKey in each CWR which may not match x-org-id. thus we will use Archive schema.Archive instead of Key schema.AMKey for the CWR. after validating the MetricData orgid, we can then generate the proper key for the CWR
3) importer-writer has no need for a cli flag for orgId enforcement, and can accept whatever was sent to it (once 1 and 2 are implemented)
4) importer-reader needs no orgid option, as that'll be set automatically via auth.

**Comment by replay** [comment]
that's correct as you described. the only PR left to merge is the MT one (https://github.com/grafana/metrictank/pull/1335), the HM-API & tsdb are already merged
