### ISSUE TITLE
Find cache threads don't get stopped correctly

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1340]
When we stop the find cache via the `Shutdown()` function, one object gets pushed into `c.shutdown` to notify the go routines to shut down. But there are 2 go routines, only 1 of them will consume this object that's been pushed, the other one will keep hanging. So it's leaking routines. During normal MT operations this doesn't matter, but when running tests it can be annoying because sometimes i see stack traces with 20 find cache routines that are still lingering.
Furthermore, many tests instantiate and re-instantiate the index many times, but don't shut it down before re-instantiating it. 
Both the above things would need to get fixed to get rid of the leaking find cache routines when running the tests.

**Comment by woodsaj** [comment]
The problem here is more then just FindCache.Shutdown() writing to the channel instead of just closing it.

FindCache.Shutdown() is simply never called.

https://github.com/grafana/metrictank/blob/master/idx/memory/memory.go#L278-L280

it should be called from within the UnpartitionedMemoryIdx.Stop() call.  eg
```
func (m *UnpartitionedMemoryIdx) Stop() {
	if m.findCache != nil {
		m.findCache.Shutdown()
	}
	return
}
```
