### ISSUE TITLE
Remove the ability to change partitions in the index at runtime

### ISSUE THREAD

**Issue by robert-milan** [grafana/metrictank#1367]
Let's remove the ability to change partitions at runtime. This would greatly reduce the complexity of the index in general, and get rid of some atomic operations (which is almost always a good thing)

Is there an actual use case for changing partitions at runtime? With all of the ongoing migration work I think we can safely get rid of this.

**Comment by Dieterbe** [comment]
IIRC we added this functionality to make sure we could make tweaks to our partitioning scheme without breaking anything. Maybe @woodsaj can think of another reason.

Keep in mind that not everyone running metrictank
1) uses the same partitioning. in particular @shanson7 comes to mind as they have C++ code as the source of their metrics, and they effectively have their own partitioning scheme.
2) will be as comfortable doing cluster migrations as we are

**Comment by woodsaj** [comment]
There is no good reason to try and handle partition changes.  I think the code was there to allow for the possibility, but users would have a really bad experience if they changed the partition assignments on a running cluster.
- if the partition changed, data would likely be routed to different nodes in the cluster.  This would lead to:
  - data would be lost.  The new node would start a new chunk part way through the chunk span and flush it when a datapoint for the next chunk is received.  At a later point in time when chunk GC is run, the old node will flush the partial chunk it has, overwriting the previously written chunk.
  - Users would receive inconsistent query results as some requests would go to the old node and some to the new node.
https://github.com/grafana/metrictank/blob/master/api/graphite.go#L303-L315  
This problem would persist until the old node(s) are restarted.  Because we currently do delete the entry for the old partition from cassandra/bigtable, when the old node restarts it wont reload the index entries.

So given that the experience of changing the partition is so bad, i think we should just remove the capability.

**Comment by shanson7** [comment]
We have so far never changed our partitions. I don't think that it would work nicely (as @woodsaj mentions). I'm in favor of this for simplicity, but are there any benchmarks indicating that these atomic operations are actually all that expensive?

**Comment by robert-milan** [comment]
We don't have any benchmarks yet, it has to do more with actually maintaining and improving the code as we move forward.

**Comment by shanson7** [comment]
I only mention because of the `perf` label

**Comment by robert-milan** [comment]
I see your point, I'm not sure if it deserves the `perf` label or not. I will say that it removes an allocation in hotpaths (`update`, `addorupdate`), but it might not actually be worthy of the `perf` label.
