### ISSUE TITLE
divideSeries needs len dividendseries to equal len divisor series

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1461]
currently we enforce that there's 1 divisor, but there should be the same number as the number of dividendseries.

actually, i like the idea of having multiple dividends, being divided by 1 divisor, but that's not what graphite does. maybe if @DanCech or @replay has time to fix it in Graphite , we can keep that functionality.

**Comment by replay** [comment]
Actually the docs sound to me like it is already supposed to do what you suggest: https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.divideSeries

Because the second argument in `divideSeries(dividendSeriesList, divisorSeries)` is `divisorSeries` and not `divisorSeriesList` like in the function `divideSeriesLists()`. In that case, this would be a bug if it currently doesn't do it that way.

**Comment by Dieterbe** [comment]
right.
seems like the graphite docs and the code agree that:
* divideSeriesLists() divides equal-length (possibly 1) seriesLists by one another.
* divideSeries() divides seriesList by a single series (or by no series in which case it only adjusts the name)
