### ISSUE TITLE
improve error handling in query pipeline to set proper http codes

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1462]
e.g. FuncDivideSeries.Exec does this:
```
        if len(divisors) != 1 {
                return nil, errors.New(fmt.Sprintf("need 1 divisor series, not %d", len(divisors)))
        }
```

which result in http 500, but should be http 400

**Comment by woodsaj** [comment]
we already have an 'Error' interface defined in the api/response package.
https://github.com/grafana/metrictank/blob/master/api/response/error.go#L11-L14

If you have the expr package return errors that implement this interface, then they will be returned with the correct status code.

eg. 
The errors in expr/parse.go: https://github.com/grafana/metrictank/blob/master/expr/parse.go#L16-L24

can just use `response.NewError(http.StatusBadRequest, "argument missing")` instead of `errors.New("argument missing")`

The other errors in this file that are using their own structs, just need to have a "Code() int" function added so they implement the interface.

eg
```
type ErrBadArgument struct {
	exp reflect.Type
	got reflect.Type
}

func (e ErrBadArgument) Error() string {
	return fmt.Sprintf("argument bad type. expected %s - got %s", e.exp, e.got)
}

func (e ErrBadArgument) Code() int {
  return http.StatusBadRequest
}
```
