### ISSUE TITLE
circuit breaker for cassandra

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#147]
if MT is seeing long requests and timeouts to cassandra, it should break the circuit

**Comment by ctdk** [comment]
But it should also try to reconnect periodically to cassandra when it does time out. We were seeing last night that it wasn't.

**Comment by Dieterbe** [comment]
oh and it should also log connection attempts, log successes/failures, explain its decisions

**Comment by woodsaj** [comment]
This is all either allready done or irrelevant.

The problems seen over the last few days were not because of cassandra.  Cassandra issues were a result of metricTank bugs resulting in an insane volume of requests being sent to cassandra. 

The only thing that is really needed is to ensure that cassandra reads cant consume all of the connections in the cassandra pool.  Though this will be addressed when we move to Kafka

**Comment by Dieterbe** [comment]
we shouldn't restrict improvements to only what would have helped with past issues. a circuit breaker is a good safeguard to have and I think we should definitely add that functionality at some point. It will protect us from bringing cassandra down in the future, whether users/customers are flooding requests, or wether we're accidentally doing it ourself.
