### ISSUE TITLE
RE: mt-whisper-importer-writer

### ISSUE THREAD

**Issue by Nuadvocate** [grafana/metrictank#1475]
This is more of a question than a request.

When migrating metrics from whisper to metrictank/cassandra using this tool, it overwrites existing data, and sometimes replaced the data with the timestamp of the configured "to" and "from" with a non-value, thus creating gaps between metrics.

Are there specifics options to not overwrite existing data?

**Comment by replay** [comment]
The reader has a cli argument `-write-unfinished-chunks` which controls whether it should generate and submit chunks even if there isn't enough data to completely fill the chunk. The is to prevent situations where incomplete chunks would get stored because there isn't enough input data to fill their chunk span.
