### ISSUE TITLE
Names / tag values with space character break certain functions

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#1672]
At least `aliasSub` and `aliasByTags` have an issue. I think it could be related to the space character not being in https://github.com/grafana/metrictank/blob/5eedf842a8852fdd4ee310229c26b9755c3fb08d/expr/parse.go#L283

**Comment by replay** [comment]
I created a metric called `some.test metric.abc.1` with a bunch of tags. I can reproduce a querying issue when querying by metric name:

```
replay@mst-nb:~$ curl 'http://localhost:6061/render' -d 'target=some.test metric.abc.1' -d 'format=json'
failed to parse "some.test metric.abc.1" fully. got leftover " metric.abc.1"
```

I think you're right that this is due to the space missing in `expr/parse.go:283`.

But when using `aliasByTags()` it appears to work fine, at least like this:

```
replay@mst-nb:~$ curl -s 'http://localhost:6061/render' -d 'target=aliasByTags(seriesByTag("name=some.test metric.abc.1","secondkey!="),"secondkey","name")' -d 'format=json' -d 'maxDataPoints=1' | jq
[
  {
    "target": "anothervalue1.some.test metric.abc.1",
    "tags": {
      "goodforpeoplewhojustusetags": "forbasicallyeverything",
      "region": "west",
      "afewmoretags": "forgoodmeasure",
      "lotsandlotsoftags": "morefunforeveryone",
      "onetwothreefourfivesix": "seveneightnineten",
      "thirdkey": "onemorevalue",
      "anothertag": "somelongervalue",
      "secondkey": "anothervalue1",
      "name": "anothervalue1.some.test metric.abc.1",
      "manymoreother": "lotsoftagstointern",
      "os": "ubuntu"
    },
    "datapoints": [
      [
        0.5018836629838438,
        1581970260
      ]
    ]
  }
]
```

Could you show an example of how `aliasByTags()` is broken?

**Comment by shanson7** [comment]
> Could you show an example of how aliasByTags() is broken?

When using nodes, e.g. `aliasByTags(1)`

**Comment by replay** [comment]
I confirmed that by adding the space char to the `nameChar` var on `expr/parse.go` the described issues disappear. I tested by querying the metric by name, and also by querying it by tag and using the `aliasByTags()` function. in both cases i was able to reproduce the described issue with `master` but once i added the space char to `nameChar` the issue was solved.
I'm unsure though if we really want to allow space chars in metric names. I think the best argument for doing so is that graphite allows it, on the other hand carbon doesn't because it would break the carbon line protocol, so realistically probably almost no graphite users actually use spaces in their metric names.
