### ISSUE TITLE
live upgrades don't work when changing chunkSpan

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#169]
chunks are identified by their t0 so when you start a new instance that uses different chunkSpans:
- if its chunkspan is longer than the chunkspan used by the primary it will drop data, once that chunk has been saved (we saw this happen in an attempted upgrade from 10min to 30min chunkSpan: `cant write to chunk that has already been saved. 1404.6e2293c9f8330acdb18e520229184417 T0:1457328600`)
- or fail to add new data to finished chunks that the primary is still using (presumably)

**Comment by woodsaj** [comment]
Though we are seeing the error that saved chunks cant be written to due to the the difference in chunkspans between the two nodes, the error could also happen if the non-primary node is processing metricPersist messages faster then metricData.  This will result in the aggMetric being marked as saved before all data has been read from NSQ.

I think the best option here is to move the logic for preventing metrics being added to saved Chunks to go-tsz.  
https://github.com/dgryski/go-tsz/blob/master/tsz.go#L69
Series.Push() should be extended to return an error, and after obtaining the Lock, check of the chunk is finished or not. If finished it should return an error.  This will allow us to continue to use the aggMetric.Saved attribute to flag whether chunks need to be persisted to cassandra, but not prevent new points being added.  

Migrating an installation from one chunkspan to another should just be documented well so that the admins take extra precautions when making the switch to prevent data loss.
For us the process would be.

1. build up the cache on the new node which has a larger chunkspan. 
2. Once the cache is full, the new node can only be promoted after its chunkspan boundary and shortly before the chunkspan boundary of the existing node. eg.
if the existing chunkspan is 10mins, and the chunkspan of the new node is 30mins, then the new node would need to be promoted at 09 or 39 minutes past the hour.
