### ISSUE TITLE
Incorrect normalization causes panic

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#1811]
**Describe the bug**

Relevant stack:
```
/metrictank/expr/seriesaggregators.go:147 (0xbc58bd)
/metrictank/expr/func_aggregate.go:74 (0xb98a3d)
/metrictank/expr/func_aggregate.go:61 (0xb97fea)
/metrictank/expr/plan.go:309 (0xbc4dcb)
/metrictank/api/graphite.go:844 (0xc39bf4)
/metrictank/api/graphite.go:268 (0xc32d0e)
```

I was able to narrow the crash down to a query like `sum(a, summarize(a, '10min'))`, where the lcm used to normalize is 600 (e.g. interval of a is a factor of 600). It seems that summarize adds in an extra datapoint at the beginning (pre-marking, as graphite does) so it has an extra datapoint after normalization.

It seems that perhaps summarize should be following almost identical logic to `normalizeTo` (with some exception for the `alignToFrom` case). This would result in postmarked result, but would be compatible for all later normalization.

**Comment by Dieterbe** [comment]
@shanson7 what version was this? please always mention the version

**Comment by shanson7** [comment]
Lately it's been a (possibly significant, based on the number of outstanding PRs) modified version of master at the time of posting. I believe this one is from this BB release branch https://github.com/bloomberg/metrictank/tree/release_20200429 which boils down to this commit https://github.com/grafana/metrictank/commit/75884f2f5f73ccb8010a9f4e9a4561eccb838a47

**Comment by Dieterbe** [comment]
I can produce this with v0.13.1-800-g74ba401c
hold on for formatted stacktrace

**Comment by Dieterbe** [comment]
Yeah I'll update this soon with more info, but I think the gist of it is that summarize does not return series in canonical form, whereas basically everywhere else in the code we do, and we assume that we have canonical series everywhere.

**Comment by Dieterbe** [comment]
Note that `summarize(alignToFrom=true)` does something truly exceptional in terms of the kind of series it creates (and timestamps it sets), it looks very different from any other series generated anywhere else (fetching, normalizing, and any other function call all result in canonical series)

So we could add a "plan validator": after constructing the AST we can detect if a query wants to run `summarize(alignToFrom=true)` and then somehow combine that result with other -canonical- series by means of aggregate(), groupByTags, sumSeries, asPercent, etc etc.
But frankly, I rather just discourage or deprecate that param, or - since it seems so rarely used - we can leave it to panic the query with a non-optimal message.

The more interesting case is alignToFrom=false.

> This would result in postmarked result, but would be compatible for all later normalization.

Switching wholesale to postmarking is a non-trivial departure from how graphite does things, and wouldn't really solve the problem: it would still create an excess datapoint, except this time it would lie at the end (and have a ts > from), also resulting in a non-canonical series. And plotting it in Grafana would create a shifted graph because between graphite and metrictank, all points would be moved over by `interval`.

Because the current implementation returns a first point that lies before `from` (!) and actually is not plotted by Grafana anyway, I think we can simply stop returning that first point. Visually in Grafana, it would look exactly the same, though json api users might notice the first point being removed. But it seems much less impact this way.

**Comment by Dieterbe** [comment]
To demonstrate, I ran `build/mt-fakemetrics backfill --metricname fakemetrics.sine.max --value-policy daily-sine:4000,15h,1000 --mpo 1 --period 10s --speedup $((7*3600*24)) --offset $((366*24))h --kafka-mdm-addr localhost:9092` in docker/docker-dev-custom-cfg-kafka
and ran this query:

![screen](https://user-images.githubusercontent.com/20774/84651829-395f2e80-af13-11ea-855b-931c2cba3a2b.png)

`summarize()` returns:
```
metrictank_1    | (models.Series) {
metrictank_1    |  Target: (string) (len=46) "summarize(fakemetrics.sine.max, \"1min\", \"max\")",
metrictank_1    |  Tags: (map[string]string) (len=3) {
metrictank_1    |   (string) (len=9) "summarize": (string) (len=4) "1min",
metrictank_1    |   (string) (len=17) "summarizeFunction": (string) (len=3) "max",
metrictank_1    |   (string) (len=4) "name": (string) (len=20) "fakemetrics.sine.max"
metrictank_1    |  },
metrictank_1    |  Interval: (uint32) 60,
metrictank_1    |  QueryPatt: (string) (len=46) "summarize(fakemetrics.sine.max, \"1min\", \"max\")",
metrictank_1    |  QueryFrom: (uint32) 1592217212,
metrictank_1    |  QueryTo: (uint32) 1592217572,
metrictank_1    |  QueryCons: (consolidation.Consolidator) NoneConsolidator,
metrictank_1    |  Consolidator: (consolidation.Consolidator) NoneConsolidator,
metrictank_1    |  QueryMDP: (uint32) 0,
metrictank_1    |  QueryPNGroup: (models.PNGroup) 0,
metrictank_1    |  Meta: (models.SeriesMeta) (len=1 cap=1) {
metrictank_1    |   (models.SeriesMetaProperties) {
metrictank_1    |    SchemaID: (uint16) 1,
metrictank_1    |    Archive: (uint8) 0,
metrictank_1    |    ArchInterval: (uint32) 10,
metrictank_1    |    AggNumNorm: (uint32) 1,
metrictank_1    |    AggNumRC: (uint32) 0,
metrictank_1    |    ConsolidatorNormFetch: (consolidation.Consolidator) MaximumConsolidator,
metrictank_1    |    ConsolidatorRC: (consolidation.Consolidator) NoneConsolidator,
metrictank_1    |    Count: (uint32) 2
metrictank_1    |   }
metrictank_1    |  },
metrictank_1    |  Datapoints: ([]schema.Point) (len=7 cap=2000) {
metrictank_1    |   (schema.Point) {
metrictank_1    |    Val: (float64) 3455.175078391423,
metrictank_1    |    Ts: (uint32) 1592217180
metrictank_1    |   },
metrictank_1    |   (schema.Point) {
metrictank_1    |    Val: (float64) 3622.6372240166997,
metrictank_1    |    Ts: (uint32) 1592217240
metrictank_1    |   },
metrictank_1    |   (schema.Point) {
metrictank_1    |    Val: (float64) 5036.329772566606,
metrictank_1    |    Ts: (uint32) 1592217300
metrictank_1    |   },
metrictank_1    |   (schema.Point) {
metrictank_1    |    Val: (float64) 4193.290146187953,
metrictank_1    |    Ts: (uint32) 1592217360
metrictank_1    |   },
metrictank_1    |   (schema.Point) {
metrictank_1    |    Val: (float64) 5660.382271043138,
metrictank_1    |    Ts: (uint32) 1592217420
metrictank_1    |   },
metrictank_1    |   (schema.Point) {
metrictank_1    |    Val: (float64) 5059.803464757296,
metrictank_1    |    Ts: (uint32) 1592217480
metrictank_1    |   },
metrictank_1    |   (schema.Point) {
metrictank_1    |    Val: (float64) 2827.522883078393,
metrictank_1    |    Ts: (uint32) 1592217540
metrictank_1    |   }
metrictank_1    |  }
metrictank_1    | }
```
canonical output would have first TS 1592217240 and last TS 1592217540, so 6 points in total.
Note that the first point with TS 1592217180 is not even shown in Grafana
