### ISSUE TITLE
Short pauses cause kafka priority to be misreported

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#1818]
MT uses [a Ticker in trackStats](https://github.com/grafana/metrictank/blob/42045e18859f857cea40a300bdc54121a4f14498/input/kafkamdm/kafkamdm.go#L344) to check the kafka offsets/lag every second. However, if there is a pause for any reason (extra long GC, slowness fetching offsets from kafka, etc) the ticks will accumulate and MT will sample very quickly and end up with a priority calculated over a very short time window. This can lead to skewed priority calculations and instances being marked unavailable.

It seems like MT should just use a sleep here, since exact intervals aren't required for the tracking code.

**Comment by shanson7** [comment]
This is still an issue that I encounter.

**Comment by shanson7** [comment]
> This can lead to skewed priority calculations and instances being marked unavailable.

Instances being marked unavailable can result in 503s being returned to callers. That's bad. Combined with #1817 we would see thousands of request failures stemming from this occurring in a single instance of MT in the cluster.

**Comment by Dieterbe** [comment]
So, you're saing the process' priority is incorrectly high. it is set via `cluster.Manager.SetPriority(k.lagMonitor.Metric())`
Thus if `LagMonitor.Metric()` is incorrectly high, it means `getPartitionPriority` returned an incorrectly high `Status.Priority` field, which means either of these cases is happening:
```
		// if we're not sure of rate, we don't want divide by zero
		// instead assume rate is super low
		if status.Rate == 0 {
			status.Priority = status.Lag
		} else {
			status.Priority = status.Lag / status.Rate
		}
```
(where Lag is the lowest from the `lagLogger.measurements` and rate is computed by comparing the oldest vs latest from `lagLogger.measurements`). the number of measurements to track is hardcoded to 10 (`kafkamdm.New()` calls `NewLagMonitor(10, partitions)` ). 

So it sounds like what you're saying there is a pause that somehow causes bad values in all 10 of the measurements. so 10 very fast ticks in a row?

When I try to reproduce something like that, I fail. E.g. a 4second pause does not cause 4 very fast ticks
```
package main

import (
	"fmt"
	"time"
)

func main() {
	ticker := time.NewTicker(time.Second)
	var iterations int
	for ts := range ticker.C {
		fmt.Println(time.Now(), "received tick", ts)
		iterations++
		if iterations == 1 {
			fmt.Println("sleeping 4s")
			time.Sleep(4 * time.Second)
		}
	}
}
```

**Comment by Dieterbe** [comment]
ping @shanson7 -- see above

**Comment by shanson7** [comment]
> When I try to reproduce something like that, I fail. E.g. a 4second pause does not cause 4 very fast ticks

Yes, after  looking more it seems like this I was incorrect on that. The issue seems to stem from the fact that *most* of our data is published on a 30s interval  and the lagMonitor is hardcoded to measure on only a 10s interval. This means that the average "Rate" over a 10 second interval just prior to a large amount of incoming 30s data will be  artificially low so a small  amount of lag (maybe a few seconds due to the burst) will look like multiple minutes of lag. I think that perhaps the easiest solution is to make the lag monitor window size configurable.


Note: This issue has been much less noticeable since moving to the priority lock which drastically reduces short periods of lag in ingestion.

**Comment by Dieterbe** [comment]
So we have 2 hardcoded values:

* the number of measurements (hardcoded to 10)
* the reporting interval (hardcoded to 1 second)

you're right that these could be turned into config options, but i'm not sure we need to.

What i'm noticing is that in `getPartitionPriority` we take the *minimum lag seen* (across the 10 measurements) and divide it by the *average rate* (averaged across those same 10 measurements).  We could consider taking the lag and rate from the same set of measurements.
When the burst is included in the measurements, this would actually be an advantage and reduce the priority.

E.g. If your measurements are like (a bit of an extreme example for demo purposes):
| lag | rate |
|-----|----- |
| 1 | 5 |
| 1 | 5 |
| 1000 | 500k |

Then priority would become `priority = 1/166670`. A very low value indeed.

Now, you're talking about a different situation: a scenario before the burst happens, where all rate measurements are low, such that the lag factor is amplified in the formula. But again, since we take the *minimum lag seen* (across the 10 measurements), this would mean for this problem to occur, all 10 measurements should be problematic. (have an atypically high lag). So when does that happen? Either of these two:

1) the process blocks simply throughout all measurements and has, or builds up, an actual lag over the full 10s period.
2) all measurements are somehow fallacious due to blocking behavior

In case 1, it seems that the lag/rate formula works as intended. If the ingest rate is small, but yet the lag remains high enough throughout the observation window, then we can fairly say there is a high delay. That said, I suppose we have to be mindful of buffering in the client library. If the rate is that low, that throughout the entire observation window of 10s, a full batch worthwhile of fetching, is not assembled. then you may want to tweak your buffering settings. I suspect insufficient amount of data may lead to a higher lag and lower rate if the flow is too low for the configured batching. (that said, we have a few idle clusters and I haven't observed this problem).  As soon as 1 batch is fetched each observation window, this problem should disappear.

For case 2, we already established above that the ticker loop being blocked does not cause a barrage of multiple ticks.
Though what does happen is a tick for a prior timestamp will show up later. leading to a `measurement.ts` to have a value that is too low wrt its corresponding offset/watermark values. (especially if the process is cpu constrained and the ticker loop doesn't execute when it wants to).  Possibly this happens multiple times if it's a recurring problem. The only place these values are used is in the rate calculation, where it may lengthen or shorten the "duration" window calculated wrt the corresponding watermark values, leading to an inflated or deflated rate value. But I can't imagine this being very significant unless the blocking is very prolonged.
For example: if the oldest measurement came from a tick with a 10s delay due to a 10s block, then the rate will be reported as half what it should be (or rather what it could have been. it becomes tricky to speculate here what is supposed to be the correct rate without knowing prior values). If this happened for the latest measurement, then the reported rate would be twice the rate we could have reported otherwise. (but same caveat)
Similarly though in the actual reporting loop, blocking can happen at any point, so the other numbers can be off too. But we haven't really obsessed about these edge cases before so I doubt we should now.


Where does this leave us? I'm not sure. Definitely, having at least some flow of data going at all times (in particular during each 10s window) seems sensible.  Making the number of measurements (or the ticker interval) configurable seems appealing, and it depends on the configured max-priority value. If you have a max-priority of 60, then we should probably look at 60s worth of observations, to minimize the 2 cases mentioned above.

**Comment by Dieterbe** [comment]
ping @shanson7 your thoughts on the above?

**Comment by shanson7** [comment]
I think being able to configure the window for the lag calculation (or using max-priority as you mention) seems fine. I haven't seen this issue in a while since changing the locking mechanism of the index.

**Comment by Dieterbe** [comment]
this does bring additional complexity to the operator (yet another config setting), for unclear gains, and it no longer seems useful.
i propose we just close this

**Comment by shanson7** [comment]
Let's close this. I'll open a new one if I see any reproducible issues.
