### ISSUE TITLE
configuration management

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#456]
I feel that the current configuration handling is complicated and difficult to work with.

I think we need to move to a central configuration store that all packages can then use.  As well as simplifying how configuration options are registered, it also exposes all configuration options to all packages within the code base.

A couple of options come to mind:
1)
After a quick search, https://github.com/spf13/viper looks like a good candidate for handling config files, flags and env vars.  But to support parsing and validation we will need an additional layer of abstraction.

2)
Provide a single package for settings to be stored providing a bit more structure and make minor changes to how we register/validate configuration paramaters.

eg, something like
```
package setting

type Setting interface {
  Validate() error
} 

var Settings map[string]Setting

func Register(prefix string, setting Setting) {
  Settings[prefix] = setting
}

func Get(prefix string) Setting {
  return settings[prefix]
}
```
------------------------
```
package api
import "metrictank/setting"
type Settings struct {
  Port int
  SSL bool
}

func (s *Settings)Validate() error {
  if s.Port < 0 || s.Port > 65535 {
     return errors.New("invalid port number)
  }
  return nil
}

func init() {
  s := &Settings{
    Port: 6060, 
    SSL: false,
  }
  setting.Register("http", s)
  apiCfg := flag.NewFlagSet("http", flag.ExitOnError)
  apiCfg.IntVar(s.Port, "port", 6060, "TCP port for http API to listen on")
  apiCfg.BoolVar(s.SSL, "ssl", false, "Use https for api")
  globalconf.Register("http", apiCfg)
}

func Start() {
  cfg := setting.Get("http").(*Setting)
  fmt.Printf("starting on port %d", cfg.Port)
}
```

**Comment by Dieterbe** [comment]
> I feel that the current configuration handling is complicated and difficult to work with.

how so? what do you find complicated or difficult?

> it also exposes all configuration options to all packages within the code base.

any idea where we would want to leverage that?


my main gripe with our configuration is that config files is a dated concept. it makes it hard to make certain changes runtime adjustable, and it creates room for differences between settings at runtime and what's in the config.  it also makes it hard for MT instances to make changes to settings to their own, or their peers' settings. one thing that is nice about viper is it also integrates with etcd, so that you can manipulate values at runtime, updating both the source of truth as well as MT's view at once. and instances can independently alter their own configuration, updating the source of truth.
for example primary status could be managed this way.

**Comment by woodsaj** [comment]
> how so? what do you find complicated or difficult?

having to call configLoad then configProcess from main.go.

> any idea where we would want to leverage that?

The way we have to pass the logLevel around to various packages. I also need to use the the httpAPI listenAddr within the new peerDiscovery in the cluster package.

> my main gripe with our configuration is that config files is a dated concept.

I really disagree with this.  The number of configurable parameters in MT make it necessary to have a configuration file. Flexibility in platforms like docker and k8s can be achieved by dynamically building the configuration before launching MT. But a combination of both configurationFiles + commandLine args + evn vars is still the most powerful option.

runtime configuration changes are a whole other problem. Etcd is an extra dependency we dont need.  live configuration changes can be easily implemented through an API interface or simply through re-reading a config file periodically.  However many of our configuration params can't be changed on a running MT instance and for those that can be changed it would require a significant amount of refactoring to make it possible.

**Comment by Dieterbe** [comment]
> having to call configLoad then configProcess from main.go.

@replay figured out you can just use `init()` (called automatically by runtime) instead of `configLoad`. see mdata/cache/ccache.go - i have just verified that both config file override and override through env (`MT_CHUNK_CACHE_MAX_SIZE`) works as expected with this approach.
We still need something like ConfigProcess though, for app level validation of the configs, config post-processing etc. As this logic needs to be defined in the "module" (index implementation, input plugin, cache module, etc) I don't see a way around this.

> The way we have to pass the logLevel around to various packages

true. our current approach to communicating settings to other packages is simplistic and not the most elegant.  But at least it's simple and obvious and only uses simple language features, as opposed to being hidden in abstraction layers or libraries. I personally draw inspiration from the go language and standard library, where often things have to be done in a bit of an ugly or low level way, favoring simplicity. rather than providing richer api's and functionality which make things more complicated.

> live configuration changes can be easily implemented through an API interface or simply through re-reading a config file periodically

if doing it through an api, then we have the problem of drift between source of truth (config file on disk, chef, whatever) and runtime config which can be very dangerous (e.g. a restart of MT might break things)
if doing it by deploying a new config file (whether through config management like chef or re-generating it with k8s) and having MT re-read the file, then:
1) that's a symptom that the config file was an unnecessary step and we could hook up MT more directly to the source of thruth. (however i'll be quick to acknowledge that filesystems and their api's are probably the most mature and solid mechanism for configuration, even when not perfect. so pragmatically speaking, it's fine to go via a config file, i'm just being a bit utopic here, as you know i can sometimes be, so while i wanted to share this POV I have no issues classifying this argument as not realistic enough and can be ignored. however my following argument is more real I think.
2) we have the problem that the new file might make changes to settings that are not supported to be runtime-changed (in addition to valid changes), and we run into the situation again that what's on disk (or what's known to the source of truth) may not match what's the runtime config.

> However many of our configuration params can't be changed on a running MT instance and for those that can be changed it would require a significant amount of refactoring to make it possible.

Sure I agree with that. But we know that we'd like certain settings to be runtime changeable at some point (a few that come to mind: warmup, log level, chunk cache parameters)
I'm not saying we should go do that now, but as we look into leveling up on our configuration system, I think we should keep this in mind.

**Comment by Dieterbe** [comment]
related: #175

**Comment by woodsaj** [comment]
I feel that if we can provide a way to dump the config from a running instance of MT, then the on-disk config and the running config being out of sync no longer become a problem.  Moving all of the configuration into a central package makes retrieving the running configuration a possibility.

**Comment by Dieterbe** [comment]
> I feel that if we can provide a way to dump the config from a running instance of MT, then the on-disk config and the running config being out of sync no longer become a problem

so metrictank itself becomes the source of truth for its own configuration? not CM/k8s ? you'd hit a network api on metrictank to adjust runtime config, and then it would validate the change, and when valid, apply the change + persist to file?

**Comment by woodsaj** [comment]
I think you are over thinking this.

Only the running application can be the source of truth for what the configuration is.  But the configfile + commandLine args + environment variables (however that his managed) will be the source of truth for what the configuration should be. This is true for just about every application.

The only way to truly make a configfile (or other medium) the source of truth is for the application to be able to "reload" the configuration by some mechanism, often just a restart.  That is not an option for MT as we cant change many of the variables on a running instance and restarting has a significant performance penalty. 

There are 2 things we want:

1) always know exactly what variables a running instance is using.  This is really only needed for troubleshooting problems. For this, we should just have an API endpoint that returns the current config.

2) be able to update some variables on a running instance. We already do this for the cluster.Primary setting using an API, and we should stick with that approach.  There is no need to make MT sync that change to the config file. As is the case for the primary setting, we dont always want the "initial" value to be used at startup (loaded from the configfile) to be the same as the current setting.

**Comment by Dieterbe** [comment]
Ah, so we're explicitly saying that config file / CM (chef) is not the source of truth.  And instead rely on operator precaution to deal with any drift or mismatch when doing maintenance tasks or restarts.
That's fine with me, I try to do this already anyway (and getting a dump from the instance will make this much easier), I just was under the impression that we wanted our CM/chef to be the source of truth, that's how it's usually thought of anyway, but that doesn't really work with MT and as long as we're explicit about it, that works, I think. We're switching to k8s which is quite different but I think the considerations and tradeoffs are the same there. 

So, back to the more concrete points.
for accessing other module's config values, can't we just use exported package variables?
https://golang.org/ref/spec#Program_execution says
> If a package has imports, the imported packages are initialized before initializing the package itself. If multiple packages import a package, the imported package will be initialized only once. The importing of packages, by construction, guarantees that there can be no cyclic initialization dependencies.

So, we can use `init()` in every package where we want to establish config values. and we can depend on other packages configs by importing them (which is what we would do anyway to refer to their exported values), to assure their init runs before ours. We can't have cyclic relations but that should be fine.

Using this method, the cluster could just refer to `api.Addr`.
For access to the log level, we would use a separate package which would hold it, e.g. `github.com/raintank/metrictank/log` would have a Level variable, set via its `init()` and other packages could just refer to it.

**Comment by woodsaj** [comment]
I think as a first step we can just move to defining flag variables in init(). But rather than just using package variables directly i think we should wrap config items into a struct.  This allows us to easily grab all configuration for a package and provides a more structured way of handling settings leading to cleaner code.

eg.

```
package foo

type fooSettings struct {
   Name string
   Size int
   Duration time.Duration
   durationStr string
}

// initialize a settings with defaults.  This will allow the package to work without having to 
// parse flags.
var Settings = &fooSettings{
   Name: "blah",
   Size: 10,
   Duration: time.Second,
}

func init() {
  // register our flag variables.  Defaults are defined in our package's "Settings" struct.
  flag.StringVar(Settings.Name, "name", Settings.Name, "config option called name")
  flag.IntVar(Settings.Size, "size", Settings.Size, "config option called size")
  flag.StringVar(Settings.durationStr, "duration", Settings.Duration.String(), "config option called duration")
}
func (s *fooSettings) Process() error {
   var err error
   if s.Duration, err = time.ParseDuration(s.durationStr); err != nil {
      return err
   }
   if s.Size < 0 {
      return fmt.Errorf("size must be a positive integer")
  }
  return nil
}
```
-------
```
package main
import "foo"
import "bar"

func main() {
  flag.Parse()
  if err := foo.Settings.Process(); err != nil {
   panic(err)
  }
  bar.DumpSettings()
}
```
---------
```
package bar
import foo

func DumpSettings() {
  output,_ := json.MarshalIndent(foo.Settings, "", "\t")
  fmt.Printf("%s", output)
}
```

**Comment by Dieterbe** [comment]
this looks nice. how about we add this:

```
package settings

var settings []setting

type setting interface {
   Process() error
}

func Add(s setting) {
   settings = append(settings, s)
}

```

```
package foo
(...)

func init() {
  // register our flag variables.  Defaults are defined in our package's "Settings" struct.
  flag.StringVar(Settings.Name, "name", Settings.Name, "config option called name")
  flag.IntVar(Settings.Size, "size", Settings.Size, "config option called size")
  flag.StringVar(Settings.durationStr, "duration", Settings.Duration.String(), "config option called duration")
  settings.Add(Settings)
}
(...)
```

this way, we can iterate over all settings and process them all. without having to specify all the different packages anywhere. and they would be in the same order as the init functions are called in, which respects dependencies already.
