### ISSUE TITLE
When querying very short ranges I get misleading errors

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#470]
That's an example on `metrictank-read-ops-0`:

```
$ curl -H "X-org-id: 12574" "http://localhost:6060/render?target=metrictank.stats.ops.metrictank-read-ops-0.api.request_handle.latency.max.gauge32&from=1483794000&to=1483794009"
invalid request. to must > from
```

When I make the queried range a little longer it's fine:

```
$ curl -H "X-org-id: 12574" "http://localhost:6060/render?target=metrictank.stats.ops.metrictank-read-ops-0.api.request_handle.latency.max.gauge32&from=1483794000&to=1483794010"
[{"target":"metrictank.stats.ops.metrictank-read-ops-0.api.request_handle.latency.max.gauge32","datapoints":[[null,1483794010]]}]
```

I suspect this is related to how the `from`/`to` get fixed before being passed to `AggMetric.Get()`

**Comment by woodsaj** [comment]
This is because the the to/from values get quantized before fetching data.
https://github.com/raintank/metrictank/blob/master/api/dataprocessor.go#L559

So if the both to and from can get quantized to the same value if they are less then the metric interval apart.

This is a valid query and looks like we can just change https://github.com/raintank/metrictank/blob/master/mdata/store_cassandra.go#L369 to be 

```
if start >= end {
````
