### ISSUE TITLE
Panic when nil message comes from kafka

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#677]
I'm not sure in what scenarios a `nil` will come through this channel, but this crashed all instances of metrictank at the same time with the following stack:

```
Jul 03 10:26:17 iob1-ntfs-r2n01.inf.com metrictank[10738]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 03 10:26:17 iob1-ntfs-r2n01.inf.com metrictank[10738]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa3e86b]
Jul 03 10:26:17 iob1-ntfs-r2n01.inf.com metrictank[10738]: goroutine 1762 [running]:
Jul 03 10:26:17 iob1-ntfs-r2n01.inf.com metrictank[10738]: github.com/raintank/metrictank/input/kafkamdm.(*KafkaMdm).consumePartition(0xc42040e1e0, 0xc42017de29, 0x7, 0x2a, 0xa1a70a15)
Jul 03 10:26:17 iob1-ntfs-r2n01.inf.com metrictank[10738]: /home/cloud-user/go/src/github.com/raintank/metrictank/input/kafkamdm/kafkamdm.go:258 +0x70b
Jul 03 10:26:17 iob1-ntfs-r2n01.inf.com metrictank[10738]: created by github.com/raintank/metrictank/input/kafkamdm.(*KafkaMdm).Start
Jul 03 10:26:17 iob1-ntfs-r2n01.inf.com metrictank[10738]: /home/cloud-user/go/src/github.com/raintank/metrictank/input/kafkamdm/kafkamdm.go:216 +0x31e
```

**Comment by Dieterbe** [comment]
can you share your configuration, specifically your kafka settings, specifically your kafka offset interests me. was there any information preceeding this panic? I think this might be #520

**Comment by shanson7** [comment]
Actually, the circumstances are interesting.

It seems like at some point over the weekend, MT stopped consuming from Kafka, however we were still producing messages. When we restarted a down kafka broker this morning, MT realized it was 99 Billion messages behind, and repeatedly connected and disconnected to brokers with:
```

Jul 03 10:18:41 iob1-ntfs-r2n02.inf.bloomberg.com metrictank[17351]: [Sarama] 2017/07/03 10:18:41 consumer/metrics/64 finding new broker
Jul 03 10:18:41 iob1-ntfs-r2n02.inf.bloomberg.com metrictank[17351]: [Sarama] 2017/07/03 10:18:41 client/metadata fetching metadata for [metrics] from broker iob1-ntfs-r2n03.inf.bloomberg.com:9092
Jul 03 10:18:41 iob1-ntfs-r2n02.inf.bloomberg.com metrictank[17351]: [Sarama] 2017/07/03 10:18:41 consumer/broker/0 added subscription to metrics/64
Jul 03 10:18:41 iob1-ntfs-r2n02.inf.bloomberg.com metrictank[17351]: [Sarama] 2017/07/03 10:18:41 client/metadata fetching metadata for [metrics] from broker iob1-ntfs-r2n03.inf.bloomberg.com:9092
Jul 03 10:18:41 iob1-ntfs-r2n02.inf.bloomberg.com metrictank[17351]: [Sarama] 2017/07/03 10:18:41 kafka: error while consuming metrics/64: kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.
Jul 03 10:18:41 iob1-ntfs-r2n02.inf.bloomberg.com metrictank[17351]: [Sarama] 2017/07/03 10:18:41 consumer/metrics/64 shutting down because kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.
``` 

But the crash occurred about 7.5 minutes later.

**Comment by shanson7** [comment]
It actually seems that MT got stuck on Cassandra being down (everything fell apart over the weekend for our POC). So it was stuck for about 62 hours, and then crashed when we fixed cassandra and it started reading from kafka where it had left off (which was long gone by then).

**Comment by Dieterbe** [comment]
> It actually seems that MT got stuck on Cassandra being down (everything fell apart over the weekend for our POC)

the way this should manifest is the write queue filling up, which ones it hits the limit, causes ingestion to block. (see https://github.com/raintank/metrictank/blob/master/docs/operations.md#ingestion-stalls--backpressure). if you saw something else, let me know.

>  then crashed when we fixed cassandra 
do you have logs of this?

>  it started reading from kafka where it had left off (which was long gone by then).
so, similar to #520 a crash seems an appropriate behavior here, as operator input is required.
please let me know your kafka offset setting.

**Comment by shanson7** [comment]
kafka-mdm-in offset setting was "1h", but I don't think that would factor in here, as that should only be an on startup setting.

I think that perhaps this is a corner case, as in a production setup we would have alerted far earlier in the issue.

Some things that I am a little worried about:
1. Multiple (important) metrics stopped reporting: pressure, kafka lag
2. I don't see any information about writes for the memory index. What metric would this be?
2. Killing the whole cluster at the same time results in guaranteed downtime. There is no recovery option.

**Comment by Dieterbe** [comment]
so you said 99B messages behind and you got a crash due to "The requested offset is outside the range of offsets maintained by the server for the given topic/partition." but you also say your offset is 1h. so did you accumulate 99B messages in 1 hour? (e.g. 27million per second)

> Killing the whole cluster at the same time results in guaranteed downtime. There is no recovery option.

to be clear: the only case where this is considered the reasonable thing is when an instance starts and it is configured to consume an offset from kafka that no longer exists . as an operator you can avoid being bitten by this by setting sufficient retention in kafka, adjusted for your offset; and alert yourself timely so you can restart instances without running into this case. and by doing staggered upgrades/restarts you can always assure a sufficient amount of nodes online at the same time. (e.g. we restart 1 by 1 or 2 by 2 and if we hit this kafka error, we just have it restart, because we only hit this scenario when there is a race condition between kafka announcing an offset, MT starting to consume and kafka deleting a log file, this typically requires 1 restart to resolve itself). I suggest we do a call where we can go in depth into this topic.

regarding your 1): this is unexpected and not seen before. when situations like this happen (where the process is running, but doesn't seem to be executing critical functionality, doesn't respond to requests, etc) please open a ticket with a stack trace and (optionally also) a cpu profile. both can be easily obtained live without affecting the running instance. the instructions are at https://github.com/raintank/metrictank/blob/master/docs/operations.md#metrictank-hangs

regarding 2) do you use https://grafana.com/dashboards/279 ? index metrics are on row 7
it should look something like this: 
![idx](https://user-images.githubusercontent.com/20774/27802781-37a24f58-6026-11e7-9d33-fb9e04eaff9e.png)

**Comment by shanson7** [comment]
No, the 99Billion messages accrued over the course of 60+ hours. The instances were running the whole time. This did not happen during startup.

**Comment by woodsaj** [comment]
as discussed in https://github.com/raintank/metrictank/issues/520 when a MT instance tries to read an offset from kafka that no longer exists, the only safe option is to drop all data in memory and start consuming again and this is best achieved by just restarting the process.

This scenario only occurs when your cluster is already having some pretty serious issues, so taking the whole cluster down to restore services is a pretty acceptable approach IMHO.

> Multiple (important) metrics stopped reporting: pressure, kafka lag

where are you sending these metrics? If you are sending them into the cluster then when the cluster is down you obviously won't be able to see the metrics.

**Comment by Dieterbe** [comment]
I reread this thread a couple times. I think the important take-away here is to set up monitoring so that when cassandra gives issues, you are alerted and can mitigate the issue, in a reasonable timeframe which is less then kafka retention.
also, set your kafka retention long enough precisely to allow for this timeframe.
we have a "queue drainability" alert like so:

```
groupByNodes(consolidateBy(metrictank.stats.*.*.store.cassandra.write_queue.*.items.min.gauge32, 'min'), 'maxSeries', 2, 3)

if minimum of this query over a 50 minute period is above 0, we know the queue is not able to drain, so alert
```
the 50minute period is something we chose as that makes sense for us, but you may want something else of course.
see also https://github.com/grafana/metrictank/blob/master/docs/operations.md#useful-metrics-to-monitoralert-on

also note that a bunch of this code has changed recently. see #717 

I don't think anything here is left to do. feel free to re-open if I'm wrong.
