### ISSUE TITLE
partial chunks too eagerly ignored, maybe enough to cover certain data requests

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#78]
see https://github.com/raintank/raintank-metric/pull/74#issuecomment-164574785 and https://github.com/raintank/raintank-metric/pull/74#issuecomment-164968028

**Comment by woodsaj** [comment]
This is low prio. It is a very minor performance issue that only affects queries that include data in the first chunk written. If we keep 6hours of data in memory, then the problem is only present for the first 6hours after a metric_tank process is started.

Given the limited impact, i am not even sure that the benefit of correcting this would ever be worth the cost to optimize the code.

**Comment by Dieterbe** [comment]
agreed on low prio & not sure how useful.  i suggest to keep this open until we get familiar with the impact of upgrades and secondary->primary upgrades, we'll see if cassandra takes a hit or not.
