### ISSUE TITLE
deal intelligently when multiple variants exist of a given metric, with different intervals

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#80]
for any given time range, we need to know what the interval is at each point in time, to do proper consolidation.

**Comment by woodsaj** [comment]
I think the best approach here is to incorporate the interval in the metric.ID, so changes to the interval will create a new series.

**Comment by Dieterbe** [comment]
slept on this a night, like the idea. it seems more elegant than the more complex tracking of metadata changes over time. we should consider adding a restriction so that you can't write to two variants of the same series (e.g. a foo.bar with 1min step and foo.bar with 10s step) at the same time, so that the data doesn't overlap, when the user requests foo.bar we will always use the different series with different intervals, if their data falls within the requested range right? then we need to make sure they don't have data for the same points in time.

not an issue right now. but if users start patching the probe software or their own data senders, we need to prevent this

**Comment by woodsaj** [comment]
this is related to https://github.com/raintank/raintank-metric/issues/92

the problem is a little more complex then just creating a new metricDef for each variation of interval.

If there are 2 interval variations (10 and 60), then currently both variations will be queried for.  When handling the request metric-tank will align the requests and the 10second interval data will be consolidated so that it can match the 60s interval.   However if the range requested only has 10second data then there is no need to consolidate.

So in order to be able query correctly we need to know
a) that there are multiple metricDefs for the same series
b) for each metricDef we need to know the time range that they represent.

'a' is fairly straight forward to address. but 'b' is a little more difficult. We need to track both a "created" in addition to the "lastUpdate" time.

the lastUpdate is updated every 30minutes.  So we have a decent guide to what the time range end of a metricDef is, within 30minutes of the lastUpdate time.

When querying in graphite-raintank we can use the created and lastUpdate to filter out the results we want. `created > endtime AND lastUpdate > (start - 30mins)`

eg by adding the following elasticsearch range query when searching for the last 3hours of data between 1452229869 and 1452240669.
```
"bool": {
    "must": [
		{
	        "range": {
			  	"created": {
			   		"lte": 1452240669
			  	}
			}
		},
		{
			"range": {
			  	"lastUpdate": {
			   		"gte": 1452229869 - (60*30)
			  	}
			}
		}
	]
}
```

This should get us close to a complete solution. But there are still some edge cases to work out, like the interval changing from 10s to 60s and then back to 10s

**Comment by Dieterbe** [comment]
> like the interval changing from 10s to 60s and then back to 10s

Yes we should support all variations. Maybe create a new series each time it changes. Ie also base a series on created time. Anyway i feel it would be good to brainstorm a bit on this in a hangout
