### ISSUE TITLE
better way to do api/rpc

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#822]
problems:

* manually writing and managing routing rules, payload specs, etc, manually making sure client and server are in sync
* manually maintaining documentation 

interesting technologies: 
* https://www.openapis.org/ (formerly known as swagger) can generate implementations, docs, and client libraries in other languages (AFAIK)
* https://blog.twitch.tv/twirp-a-sweet-new-rpc-framework-for-go-5f2febbf35f (seems like a well engineered and applicable library)
* http://nodir.io/post/138899670556/prpc (from the twirp article's comments)

the streaming aspects of grpc seem nice, maybe we find a good use for it. but TBH the twirp article points out so many problems with grpc i would rather use something more simple and easily debuggable

**Comment by Dieterbe** [comment]
we're also not very happy with macaron. too much magic, not popular at all. and we think it may have some leaks but we're not sure

**Comment by woodsaj** [comment]
I would love to see us move to GRPC for intra-cluster communication.
And get rid of Macaron in favour of just using the 'http' package for client facing endpoints.

**Comment by shanson7** [comment]
I think a proper versioned binary RPC framework for intra-cluster communication would be great. Things I would like from such a framework:
1. Streaming
1. Efficient encoding (protobuf?)
1. Lightweight compression (snappy, lz4)
1. Versioned requests
1. Simplified code

### Streaming 

In my tests, a significant amount of time/memory is spent encoding, sending, receiving and decoding. Obviously, reducing the message size is the most effective thing to do here. Streaming is a close second.

### Efficient Encoding

Msgp is very flexible, but since we are generating types anyway, the extra message overhead of encoding value names is wasteful. A fully binary protocol should be able to use positional elements and tag IDs to avoid encoding field names like `value` and `timestamp`. 

### Lightweight Compression

Again, in tests we found that gzip compression for intra-cluster communication was too heavy-weight and often resulted in slower response times and *more* memory usage (likely for the intermediate decompress operation). We have disabled GZIP for intra-cluster communication. Being able to use an algorithm that trades compression ratio for being much faster would be great. Again, ideally in a streaming manner. 

### Versioned Requests

Today, there is little versioning of requests for inter-operability. When enhancing existing intra-cluster requests, this can lead to downtime until rollouts are complete. It would be nice to be able to be able to enhance requests/responses in a backwards compatible manner.

### Simplified Code

Node Post currently has some fairly low-level concepts (like completely reading a body to enable re-using the connection, pushing decode off onto the caller, etc). It would be nice to use a framework that handles that and can decode directly into an object.

**Comment by Dieterbe** [comment]
I wasn't very specific in OP but it's also time to distinguish:
* intra-cluster communication
* user facing api, for which we should keep http for sure (but possibly also extend to more efficient things, but that's low prio). For this http api i would like something that can either generate docs from the code, or vice versa.

**Comment by shanson7** [comment]
I think this is still worthwhile to keep in mind, but maybe for a major version release.
