### ISSUE TITLE
add index count api call

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#965]
we get a number of customers who are looking for ways to track series growth.  
Typically there are many teams sending metrics that are prefixed by some team identifier.  

I think there are a couple of things we can do here.
1) the simplest is to just add a `/metrics/count?query=` endpoint that returns the number of series that match a query.  We just need to make sure that the query supports `prefix.**`  where the double asterisk means that the search should decend the tree.
2) a more complete solution would be to build more detailed report, such as a breakdown of series count per prefix, where the prefix length is set by the caller.  

option 2 could be easily achieved outside of metrictank with a basic script that uses option 1, so i think we should just do option 1 for now.

**Comment by replay** [comment]
When `prefix.**` is used that would also include all tagged metrics with this prefix in the name then, but i guess that's fine. Users who rely mostly just on tags to identify metrics and reuse the same metric name many times might want some way to count by tag `key`, would that be possible with this suggested solution?

**Comment by woodsaj** [comment]
TBH i haven't really thought about the how this works with tags.

**Comment by Dieterbe** [comment]
I don't think we need to collect counts based on tag keys. 
people seem to want counts based on metric name/prefix. (wherein different tags for the same key count as additional metrics, which is what we want)
There's a lot of possible implementations for this problem. Some others: keeping counts at branch nodes of number of items below. (very quick for reads, but seems probably too write-heavy), or count sketches (for certain top regions of the tree, not the entire tree)
My main reservation against the proposal here is that walking the entire index is costly, and will require holding a readlock for potentially a long time, blocking new entries, UpdateArchive calls, and deletes (and pruning). But if we partition the index (maybe into 256 or so sub-indices) then this probably becomes a non-issue

**Comment by shanson7** [comment]
We have a `namespace` tag that would be useful to get a count from. Currently we use a standalone elasticsearch cluster to do this. Having it in metrictank would save us that effort.

**Comment by Dieterbe** [comment]
@shanson7 can you clarify your use case? do you want number of metrics that have that tag (key) set, or the number for each value of that key?

**Comment by shanson7** [comment]
The number per value. More generically, this could be the number of series that match a tag query.

**Comment by replay** [comment]
If we only want to get the number of metrics per `tag` / `value` combination, that would be very easy to get because the tag index already has a structure like:

```
type TagValue map[string]IdSet    // value -> set of ids
type TagIndex map[string]TagValue // key -> list of values
```

We'd only need to get `len(index[tag][value])`

**Comment by sophosgabe** [comment]
We have the same use case as originally outlined.  We have multiple teams sending metrics and we have a pressing need to be able to measure metric ingest by metric prefix in order to monitor, control and attribute usage by team.  

Let's say my metrics match the format my.metric.prefix.<teamname>.<metric>

Ideally we'd be able to specify a metric prefix (i.e. my.metric.prefix) and receive a grouped usage "report" of all metrics under the prefix with a configurable depth.

Depth of 1 would look something like this:

my.metric.prefix.team1.* = ###
my.metric.prefix.team2.* = ###
my.metric.prefix.team3.* = ###

Depth of 2:

my.metric.prefix.team1.somemetric1.* = ###
my.metric.prefix.team1.somemetric2.* = ###
my.metric.prefix.team2.anothermetric1.* = ###
my.metric.prefix.team2.anothermetric2.* = ###
my.metric.prefix.team3.yetanothermetric1.* = ###
my.metric.prefix.team3.yetanothermetric2.* = ###

**Comment by polynomial** [comment]
We currently are struggling with autoscaling and hosted Grafana. Our metrics are of the format:
${environment}.${component}.${build-id}.${instance-id}.${metrickey1..N}

Our problem here becomes trying to leverage these across our service with dashboards, queries to try and pull identical metrics from discrete services using * cause XHR requests for the lookup in the dashboard to fail because the URLs become too large after we have shipped multiple builds. We are now building a script to delete old metrics through the API after the build is several weeks old, but it would be great if this could be handled inside of the metrics store.

**Comment by Dieterbe** [comment]
@polynomial sounds like you can just set a rule in index-rules.conf ?

**Comment by polynomial** [comment]
@Dieterbe that looks like it would work, I am unsure how to set this on our hosted grafana instance though? Is that possible somehow?

**Comment by Dieterbe** [comment]
Ah, I see you're a hosted metrics customer, I'll reach out to you via slack to get you sorted.
