### ISSUE TITLE
Timestamps returned with small MaxDataPoints value are completely wrong

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#983]
The basic issue here is that when MaxDataPoints is a small number, the time ranges that come back are completely off. This is very easy to miss when using the pie chart in grafana (which sets the MDP to 3 by default...) but users noticed when comparing graphs to pie charts.

# Metrictank 
(well, raintank tsdb on the play.grafana.org site)
[Snapshot Example](https://snapshot.raintank.io/dashboard/snapshot/j6W7UifZFiL8c1tafPB5J2bAe6poiwDp)
response:
```
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/14/render",
    "data": "target=worldping.~google_com_demo.new-york.ping.median&from=1533614400&until=1533700859&format=json&maxDataPoints=3"
  },
  "response": [
    {
      "target": "worldping.~google_com_demo.new-york.ping.median",
      "tags": {
        "name": "worldping.~google_com_demo.new-york.ping.median"
      },
      "datapoints": [
        [
          1.9022073917418467,
          1533656300
        ],
        [
          1.8690466450381682,
          1533685120
        ],
        [
          1.8561943401144299,
          1533713940
        ]
      ]
    }
  ]
}
```

# Graphite 
[Snapshot Example](https://snapshot.raintank.io/dashboard/snapshot/3o1w3rlyoffN9FYSndnf9uMcuDnEUdhL)
response:
```
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/1/render",
    "data": "target=apps.fakesite.web_server_01.counters.requests.count&from=1533614400&until=1533700859&format=json&maxDataPoints=3"
  },
  "response": [
    {
      "target": "apps.fakesite.web_server_01.counters.requests.count",
      "datapoints": [
        [
          266.5722481176049,
          1533627480
        ],
        [
          267.38693467336685,
          1533656300
        ],
        [
          258.3019243530192,
          1533685120
        ]
      ]
    }
  ]
}
```

**Comment by Dieterbe** [comment]
Request
```
~ ❯❯❯ TZ=UTC date -d @1533614400
Tue 07 Aug 2018 04:00:00 AM UTC
~ ❯❯❯ TZ=UTC date -d @1533700859
Wed 08 Aug 2018 04:00:59 AM UTC
```
MT resp
```
~ ❯❯❯ TZ=UTC date -d @1533656300 
Tue 07 Aug 2018 03:38:20 PM UTC
~ ❯❯❯ TZ=UTC date -d @1533685120
Tue 07 Aug 2018 11:38:40 PM UTC
~ ❯❯❯ TZ=UTC date -d @1533713940
Wed 08 Aug 2018 07:39:00 AM UTC
```
graphite resp
```
~ ❯❯❯ TZ=UTC date -d @1533627480
Tue 07 Aug 2018 07:38:00 AM UTC
~ ❯❯❯ TZ=UTC date -d @1533656300
Tue 07 Aug 2018 03:38:20 PM UTC
~ ❯❯❯ TZ=UTC date -d @1533685120
Tue 07 Aug 2018 11:38:40 PM UTC
```

**Comment by robert-milan** [comment]
I want to capture some discussions we have had related to this issue.

This issue mostly deals with how we address runtime consolidation and `nudging` timestamps to align properly to an interval.

- Graphite uses `premarking` and we use `postmarking`. When aggregating data in a bucket we assign the results to the last timestamp of the bucket, where graphite assigns it to the first timestamp.
- In order to align the timestamps and create reproducible and consistent queries across a shifting time window we sometimes drop a few of the initial data points and start at the first full bucket. As the Max Data Points number is set higher, less and less data is dropped from the beginning. When using a small MDP, such as 3, the difference is much more apparent.
- Sometimes the last timestamp will be further in the future than what was requested in the query. This is because of how the last timestamp is calculated during alignment.

Other effects of processing runtime consolidation in this way leads to inconsistent `sum`s across a shifting time window.

We have discussed a few options to fix this, but it requires more investigation.
- Align all data to the `end` / `to` of the request
- Include all the data at the beginning of the request. This would cause the first bucket to fluctuate over a shifting time window

**Comment by Dieterbe** [comment]
next step: robert needs to collect technical details, and then robert will schedule a call amongst maintainers to figure out next step.

**Comment by robert-milan** [comment]
After much discussion and research we have decided to keep things as they are. We will update the documentation and add a note about this behavior.
